sonar.projectKey=de6igz_devops_itmo_maga
sonar.organization=de6igz
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend/src
sonar.tests=backend,frontend/src
sonar.test.inclusions=backend/**/*_test.go,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.exclusions=backend/blob/**,backend/**/*_test.go,frontend/dist/**,frontend/node_modules/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.coverage.exclusions=frontend/src/main.tsx,frontend/src/types.ts

sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
